### ISSUE TITLE
【BUG】服务器启动报错误

### ISSUE THREAD

**Issue by ZherKing** [MrXiaoM/SweetMail#5]
插件正常运行 但是后台一直报错
系统 Debian-12.6.0
服务器核心 Paper-130-1.21

报错内容如下：
`
[11:51:39 WARN]: [SweetMail] java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:210)        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:594)        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550)
        at S[邮箱]SweetMail-1.0.0.jar//top.mrxiaom.sweetmail.func.DraftManager.receiveBungee(DraftManager.java:51)
        at S[邮箱]SweetMail-1.0.0.jar//top.mrxiaom.sweetmail.func.AbstractPluginHolder.receiveFromBungee(AbstractPluginHolder.java:60)
        at S[邮箱]SweetMail-1.0.0.jar//top.mrxiaom.sweetmail.SweetMail.onPluginMessageReceived(SweetMail.java:140)        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:197)
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26)        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13)
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)        at java.base/java.lang.Thread.run(Thread.java:1583)
`

**Comment by MrXiaoM** [comment]
BungeeCord 支持相关问题，不影响正常使用，更新到最新版解决
